= KAP 1155

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/token/kap1155

This set of interfaces and contracts are all related to the https://eips.ethereum.org/EIPS/eip-1155[KAP1155 Multi Token Standard].

The EIP consists of three interfaces which fulfill different roles, found here as {IKAP1155}, {IKAP1155MetadataURI} and {IKAP1155Receiver}.

{KAP1155} implements the mandatory {IKAP1155} interface, as well as the optional extension {IKAP1155MetadataURI}, by relying on the substitution mechanism to use the same URI for all token types, dramatically reducing gas costs.

Additionally there are multiple custom extensions, including:

* designation of addresses that can pause token transfers for all users ({KAP1155Pausable}).
* destruction of own tokens ({KAP1155Burnable}).

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in KAP1155 (such as <<KAP1155-_mint-address-uint256-uint256-bytes-,`_mint`>>) and expose them as external functions in the way they prefer. On the other hand, xref:ROOT:kap1155.adoc#Presets[KAP1155 Presets] (such as {KAP1155PresetMinterPauser}) are designed using opinionated patterns to provide developers with ready to use, deployable contracts.

== Core

{{IKAP1155}}

{{IKAP1155MetadataURI}}

{{KAP1155}}

{{IKAP1155Receiver}}

{{KAP1155Receiver}}

== Extensions

{{KAP1155Pausable}}

{{KAP1155Burnable}}

{{KAP1155Supply}}

== Presets

These contracts are preconfigured combinations of the above features. They can be used through inheritance or as models to copy and paste their source code.

{{KAP1155PresetMinterPauser}}

== Utilities

{{KAP1155Holder}}
