= KAP 721

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/contracts/api/token/erc721

This set of interfaces, contracts, and utilities are all related to the https://eips.ethereum.org/EIPS/eip-721[KAP721 Non-Fungible Token Standard].

TIP: For a walk through on how to create an KAP721 token read our xref:ROOT:erc721.adoc[KAP721 guide].

The EIP specifies four interfaces:

* {IKAP721}: Core functionality required in all compliant implementation.
* {IKAP721Metadata}: Optional extension that adds name, symbol, and token URI, almost always included.
* {IKAP721Enumerable}: Optional extension that allows enumerating the tokens on chain, often not included since it requires large gas overhead.
* {IKAP721Receiver}: An interface that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`.

OpenZeppelin Contracts provides implementations of all four interfaces:

* {KAP721}: The core and metadata extensions, with a base URI mechanism.
* {KAP721Enumerable}: The enumerable extension.
* {KAP721Holder}: A bare bones implementation of the receiver interface.

Additionally there are a few of other extensions:

* {KAP721URIStorage}: A more flexible but more expensive way of storing metadata.
* {KAP721Votes}: Support for voting and vote delegation.
* {KAP721Royalty}: A way to signal royalty information following KAP2981.
* {KAP721Pausable}: A primitive to pause contract operation.
* {KAP721Burnable}: A way for token holders to burn their own tokens.

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in KAP721 (such as <<KAP721-_mint-address-uint256-,`_mint`>>) and expose them as external functions in the way they prefer. On the other hand, xref:ROOT:erc721.adoc#Presets[KAP721 Presets] (such as {KAP721PresetMinterPauserAutoId}) are designed using opinionated patterns to provide developers with ready to use, deployable contracts.

== Core

{{IKAP721}}

{{IKAP721Metadata}}

{{IKAP721Enumerable}}

{{KAP721}}

{{KAP721Enumerable}}

{{IKAP721Receiver}}

== Extensions

{{KAP721Pausable}}

{{KAP721Burnable}}

{{KAP721URIStorage}}

{{KAP721Votes}}

{{KAP721Royalty}}

== Presets

These contracts are preconfigured combinations of the above features. They can be used through inheritance or as models to copy and paste their source code.

{{KAP721PresetMinterPauserAutoId}}

== Utilities

{{KAP721Holder}}
